#!/bin/bash

## Copyright (C) 2012 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

source /usr/libexec/msgcollector/msgcollector_shared
## sets: ${msgcollector_run_dir}
folder_init

DONE_FILE="${msgcollector_run_dir}/init_done"
SIZE="10M"

mkdir --parents "${msgcollector_run_dir}" || exit 3

if [ ! -f "$DONE_FILE" ]; then
    mount -t tmpfs -o size="$SIZE",nosuid,nodev,noexec none "${msgcollector_run_dir}" || exit 4
else
    mount -t tmpfs -o size="$SIZE",nosuid,nodev,noexec,remount none "${msgcollector_run_dir}" || exit 5
fi

touch "$DONE_FILE" || exit 6
