#!/bin/bash

## Copyright (C) 2012 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## No longer in use.
#/usr/libexec/msgcollector/msgdispatcher & disown
