#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

project_name="msgcollector"
version="0.1"

./clean

## Explicitly set access time, so we end up with a deterministic debian.tar.gz file
shopt -s globstar
touch -t "201308151102.35" ./debian
touch -t "201308151102.35" ./debian/**
shopt -u globstar

rm --force "../${project_name}_${version}.orig.tar.gz"

git archive \
   --format=tar HEAD \
   | gzip -n > "../${project_name}_${version}.orig.tar.gz"

if [ ! "$?" = "0" ]; then
   exit 1
fi

ls -la "../${project_name}_${version}.orig.tar.gz"

debuild \
   --rootcmd="debian/gain-root-command" \
   -sa

if [ ! "$?" = "0" ]; then
   exit 1
fi
