#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

error_handler() {
   local exit_code="$?"
   BUG="1"

   if [ -d /usr/share/whonix ]; then
      local MSG="<p>###############################################################################
<br></br>## $SCRIPTNAME script bug.
<br></br>## No panic. Nothing is broken. Just some rare condition has been hit.
<br></br>## Try again later. There is likely a solution for this problem.
<br></br>## Please see Whonix News, Whonix Blog and Whonix User Help Forum.
<br></br>## Please report this bug!
<br></br>##
<br></br>## BASH_COMMAND: $BASH_COMMAND
<br></br>## exit_code: $exit_code
<br></br>##
<br></br>## Experts only:
<br></br>## bash -x $SCRIPTNAME --verbose
<br></br>## for verbose output. Clean the output and report to Whonix developers.
<br></br>#########################################################################</p>"
   else
      local MSG="<p>###############################################################################
<br></br>## $SCRIPTNAME script bug.
<br></br>## No panic. Nothing is broken. Just some rare condition has been hit.
<br></br>## Try again later. There is likely a solution for this problem.
<br></br>## Please see Whonix News, Whonix Blog and Whonix User Help Forum.
<br></br>## Please report this bug!
<br></br>##
<br></br>## BASH_COMMAND: $BASH_COMMAND
<br></br>## exit_code: $exit_code
<br></br>##
<br></br>## Experts only:
<br></br>## bash -x $SCRIPTNAME --verbose
<br></br>## for verbose output. Clean the output and report to Whonix developers.
<br></br>#########################################################################</p>"

   fi
   ## Check if $output command has been already defined. This is not the case,
   ## when the script is terminated very early.
   local command_v_output_exit_code
   command_v_output_exit_code="0"
   command -v "$output" >/dev/null || { command_v_output_exit_code="$?" ; true; };
   if [ "$command_v_output_exit_code" = "0" ]; then
      $output ${output_opts[@]} --messagex --typex "error" --titlex "$TITLE" --message "$MSG" --done
      $output ${output_opts[@]} --messagecli --typecli "error" --titlecli "$TITLE" --message "$MSG" --done
   else
      local stripped_msg
      stripped_msg="$(/usr/lib/msgcollector/striphtml "$MSG")"
      if [ "$stripped_msg" = "" ]; then
         ## In case striphtml failed or is not available.
         echo "$MSG" >&2
      else
         echo "$stripped_msg" >&2
      fi
   fi

   ## Check if ex_funct command has been already defined. This is not the case,
   ## when the script is terminated very early.
   local command_v_output_exit_code
   command_v_output_exit_code="0"
   command -v "ex_funct" >/dev/null || { command_v_output_exit_code="$?" ; true; };
   if [ "$command_v_output_exit_code" = "0" ]; then
      echo "$SCRIPTNAME: Error detected. Cleaning up... Exiting..." >&2
      EXIT_TYPE="err"
      ex_funct
   else
      echo "$SCRIPTNAME: Error detected. Skipping ex_funct since not yet load. Exiting..." >&2
   fi

   exit 1
}
