#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class GuiMessage(QtGui.QDialog):
    def __init__(self):
        super(GuiMessage, self).__init__()
        self.setup_ui()

    def setup_ui(self):
        try:
            itype = str(sys.argv[1])
            title = str(sys.argv[2])
            message = str(sys.argv[3])
            question = str(sys.argv[4])
            button = str(sys.argv[5])

        except (IndexError) as e:
            sys.exit('Arguments parsing error')

        itype = "/usr/share/icons/oxygen/64x64/status/dialog-information.png"

        if str(sys.argv[1]) == "warning":
            itype = "/usr/share/icons/oxygen/64x64/status/dialog-warning.png"

        elif str(sys.argv[1]) == "error":
            itype = "/usr/share/icons/oxygen/64x64/status/dialog-error.png"

        message = message + '<p>' + question + '</p>'

        self.gridLayout = QtGui.QGridLayout(self)

        # We use QTextBrowser with a white background.
        # Set a default (transparent) background.
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.setPalette(palette)

        self.setWindowIcon(QtGui.QIcon("/usr/share/icons/anon-icon-pack/whonix.ico"))
        self.setWindowTitle(title)
        #self.resize(600, 300)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setMinimumSize(QtCore.QSize(600, 0))
        self.setMaximumSize(QtCore.QSize(600, 16777215))

        self.label = QtGui.QLabel(self)
        self.label.setPixmap(QtGui.QPixmap(itype))
        self.label.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.gridLayout.addWidget(self.label, 0, 0)

        self.text = QtGui.QTextBrowser(self)
        self.text.setMinimumSize(510, 0)
        self.text.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.text.setFrameShape(QtGui.QFrame.NoFrame)
        self.text.setFocusPolicy(QtCore.Qt.NoFocus)
        self.text.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.text.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.text.setOpenExternalLinks(True)
        self.text.setText(message)
        self.gridLayout.addWidget(self.text, 0, 1)

        self.button_group = QtGui.QGroupBox(self)
        self.button_group.setMinimumSize(0, 25)
        self.button_group.setFlat(True)

        if button == 'yesno':
            self.yes_button = QtGui.QPushButton(self.button_group)
            self.yes_button.setGeometry(370, 0, 65, 25)
            self.yes_button.setText('Yes')
            icon = QtGui.QIcon(self.yes_button)
            icon.addFile('/usr/share/icons/oxygen/16x16/actions/dialog-ok-apply.png')
            self.yes_button.setIcon(icon)
            self.yes_button.clicked.connect(self.yes_pressed)

            self.no_button = QtGui.QPushButton(self.button_group)
            self.no_button.setGeometry(440, 0, 65, 25)
            self.no_button.setText('No')
            icon = QtGui.QIcon(self.no_button)
            icon.addFile('/usr/share/icons/oxygen/16x16/actions/dialog-cancel.png')
            self.no_button.setIcon(icon)
            self.no_button.setAutoDefault(True)
            self.no_button.setDefault(True)
            self.no_button.clicked.connect(self.no_pressed)

        elif button == 'ok':
            self.ok_button = QtGui.QPushButton(self.button_group)
            self.ok_button.setGeometry(440, 0, 65, 25)
            self.ok_button.setText('OK')
            icon = QtGui.QIcon(self.ok_button)
            icon.addFile('/usr/share/icons/oxygen/16x16/actions/dialog-ok.png')
            self.ok_button.setIcon(icon)
            self.ok_button.clicked.connect(self.accept)

        self.gridLayout.addWidget(self.button_group, 1, 1)

        QtCore.QTimer.singleShot(0, self.setSize)

        self.exec_()

    def setSize(self):
        ## Size is returned
        messageHeight = self.text.document().size().height()
        maximumHeight = QtGui.QDesktopWidget().availableGeometry().height() - 60
        if messageHeight <= maximumHeight:
            self.setMinimumSize(QtCore.QSize(600, messageHeight + 60))
            self.setMaximumSize(QtCore.QSize(600, messageHeight + 60))
            self.resize(600, messageHeight + 60)
        else:
            self.setMinimumSize(QtCore.QSize(600, maximumHeight))
            self.setMaximumSize(QtCore.QSize(600, maximumHeight))
            self.resize(600, maximumHeight)

    def yes_pressed(self):
        print '16384'
        sys.exit()

    def no_pressed(self):
        print '65536'
        sys.exit()

def main():
    app = QtGui.QApplication(sys.argv)
    message = GuiMessage()
    sys.exit()

if __name__ == '__main__':
    main()
