#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2018 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## This script gets run by the /etc/xdg/autostart/msgdispatcher.desktop hook.

/usr/lib/msgcollector/msgdispatcher --x & disown
