#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## This script gets run by the /etc/xdg/autostart/msgdispatcher.desktop hook.

/usr/lib/msgcollector/msgdispatcher --x & disown
