#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -e

DONE_FILE="/var/run/msgcollector/init.done"
SIZE="10M"

mkdir --mode o+rwx --parents /var/run/msgcollector || exit 2

if [ ! -f "$DONE_FILE" ]; then
   ## ramfs does not support ACL (setfacl).
   mount -t tmpfs -o size="$SIZE" none /var/run/msgcollector || exit 3
fi

setfacl --recursive --default --set u::rwx,g::rwx,o::rwx /var/run/msgcollector || exit 4

chmod --recursive g+rwx /var/run/msgcollector || exit 5

chmod --recursive o+rwx /var/run/msgcollector || exit 6

touch "$DONE_FILE" || exit 7
