#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
from PyQt4 import QtGui
import os


class dispatch(QtGui.QMessageBox):

    def __init__(self):
        super(dispatch, self).__init__()

        self.initUI()

    def initUI(self):

        ## Cannot move to topleft safely, because of variable window size.
        ## The window moves back to center if outside screen boubaries.
        if str(sys.argv[4]) == "1":
	    self.bottomright()
        else:
	## Centered, because 'self' reference point is the center of the window.
	    self.move(0, 0)
        self.show()

        if str(sys.argv[1]) == "info":
	    self.reply = QtGui.QMessageBox.information(self, str(sys.argv[2]) , str(sys.argv[3]),
	    QtGui.QMessageBox.Ok, QtGui.QMessageBox.Ok)
	    sys.exit(0)
        elif str(sys.argv[1]) == "warning":
            self.reply = QtGui.QMessageBox.warning(self, str(sys.argv[2]), str(sys.argv[3]),
            QtGui.QMessageBox.Ok, QtGui.QMessageBox.Ok)
            sys.exit(0)
        elif str(sys.argv[1]) == "critcal":
            self.reply = QtGui.QMessageBox.critical(self, str(sys.argv[2]), str(sys.argv[3]),
            QtGui.QMessageBox.Ok, QtGui.QMessageBox.Ok)
            sys.exit(0)
        else:
            sys.exit(1)

    def bottomright(self):

        window = self.frameGeometry()
        screen = QtGui.QDesktopWidget().availableGeometry().center()
	window.moveTopLeft(screen)
	self.move(window.bottomRight())


def main():

    app = QtGui.QApplication(sys.argv)
    ex = dispatch()
    sys.exit(app.exec_())


if __name__ == '__main__':
    main()
