#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setMinimumSize(QtCore.QSize(680, maxSize + 65))
        Dialog.setMaximumSize(QtCore.QSize(680, maxSize + 65))
        Dialog.setWindowIcon(QtGui.QIcon(icon))
        if pos == "1":
            Dialog.move(0,  0)

        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(555, maxSize+30, 100, 32))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Ok)

        self.Message = QtGui.QLabel(Dialog)
        self.Message.setGeometry(QtCore.QRect(85, 10, 562, vSize))
        #self.Message.setFrameShape(QtGui.QFrame.Box)
        self.Message.setTextFormat(QtCore.Qt.RichText)
        self.Message.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Message.setWordWrap(True)
        self.Message.setOpenExternalLinks(True)

        self.Scroll = QtGui.QScrollArea(Dialog)
        self.Scroll.setGeometry(QtCore.QRect(85, 10, 585, maxSize+5))
        self.Scroll.setFrameShape(QtGui.QFrame.NoFrame)
        self.Scroll.setWidget(self.Message)

        self.Info_Icon = QtGui.QLabel(Dialog)
        self.Info_Icon.setGeometry(QtCore.QRect(10, 8, 71, 71))
        self.Info_Icon.setPixmap(QtGui.QPixmap(_fromUtf8(itype)))

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", title, None, QtGui.QApplication.UnicodeUTF8))
        self.Message.setText(QtGui.QApplication.translate("Dialog", msg, None, QtGui.QApplication.UnicodeUTF8))
        return()


if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()

    if str(sys.argv[1]) == "info":
        itype = "/usr/share/icons/oxygen/64x64/status/dialog-information.png"
    elif str(sys.argv[1]) == "warning":
        itype = "/usr/share/icons/oxygen/64x64/status/dialog-warning.png"
    elif str(sys.argv[1]) == "error":
        itype = "/usr/share/icons/oxygen/64x64/status/dialog-error.png"
    else:
        itype =""
        sys.exit("'msgdispatcher_dispatch_x'. Information type not recognized: %s" % str(sys.argv[1]))

    title = str(sys.argv[2])
    msg = str(sys.argv[3])
    pos = str(sys.argv[4])
    icon = str(sys.argv[5])

    maxvSize = QtGui.QDesktopWidget().availableGeometry().height() - 23  ## ??
    """ calculates (roughly) the vertical size of the message label """
    newlines = msg.count("<p>", 0, len(msg)) * 2
    blockquotes = msg.count("<blockquote>", 0, len(msg)) * 2
    vSize = (int(len(msg)/84) + newlines + blockquotes) * 12
    if vSize < (maxvSize-70):
        maxSize = vSize
    else:
        maxSize = (maxvSize-70)

    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
