#!/usr/bin/python
# -*- coding: utf-8 -*-

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setWindowIcon(QtGui.QIcon(icon))
        if pos == "1":
            Dialog.move(0,  0)

        self.gridLayout = QtGui.QGridLayout(Dialog)

        self.Info_Icon = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHeightForWidth(self.Info_Icon.sizePolicy().hasHeightForWidth())
        self.Info_Icon.setSizePolicy(sizePolicy)
        self.Info_Icon.setPixmap(QtGui.QPixmap(itype))
        self.Info_Icon.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.gridLayout.addWidget(self.Info_Icon, 0, 0, 1, 1)

        self.Message = QtGui.QTextBrowser(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHeightForWidth(self.Message.sizePolicy().hasHeightForWidth())
        self.Message.setSizePolicy(sizePolicy)
        self.Message.setMinimumSize(QtCore.QSize(715, 0))
        self.Message.setFrameShape(QtGui.QFrame.StyledPanel)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.Message.setPalette(palette)
        self.Message.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse | QtCore.Qt.TextSelectableByMouse)
        self.Message.setOpenExternalLinks(True)
        self.Message.setFrameShape(QtGui.QFrame.NoFrame)
        self.gridLayout.addWidget(self.Message, 0, 1, 1, 2)

        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Ok)
        self.gridLayout.addWidget(self.buttonBox, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", title, None, QtGui.QApplication.UnicodeUTF8))
        self.Message.setHtml(QtGui.QApplication.translate("Dialog", msg, None, QtGui.QApplication.UnicodeUTF8))
        ## Size is not readily available, so, create a signal
        QtCore.QTimer.singleShot(0, self.setSize)

    def setSize(self):
        ## Size is returned
        messageHeight = self.Message.document().size().height()
        maximumHeight = QtGui.QDesktopWidget().availableGeometry().height() - 25
        if messageHeight <= maximumHeight:
            Dialog.resize(830, messageHeight + 55)
            self.center()
        else:
            Dialog.resize(830, maximumHeight)
            self.center()

    def center(self):
       frameGm = Dialog.frameGeometry()
       centerPoint = QtGui.QDesktopWidget().availableGeometry().center()
       frameGm.moveCenter(centerPoint)
       Dialog.move(frameGm.topLeft())


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()

    if str(sys.argv[1]) == "info":
        itype = "/usr/share/icons/oxygen/64x64/status/dialog-information.png"
    elif str(sys.argv[1]) == "warning":
        itype = "/usr/share/icons/oxygen/64x64/status/dialog-warning.png"
    elif str(sys.argv[1]) == "error":
        itype = "/usr/share/icons/oxygen/64x64/status/dialog-error.png"
    else:
        itype =""
        sys.exit("'msgdispatcher_dispatch_x'. Information type not recognized: %s" % str(sys.argv[1]))

    title = str(sys.argv[2])
    msg = str(sys.argv[3])
    pos = str(sys.argv[4])
    icon = str(sys.argv[5])

    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

