#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

msgdispatcher_pid_check() {
   local pid_file pid

   if [ "$who_ami" = "" ]; then
      who_ami="$(whoami)"
   fi

   if [ "cli" = "$1" ]; then
      pid_file="/var/run/msgcollector/$who_ami/msgdispatcher_pidcli"
   elif [ "x" = "$1" ]; then
      pid_file="/var/run/msgcollector/$who_ami/msgdispatcher_pidx"
   else
      error "$FUNCNAME neither cli nor x is set to 1."
   fi

   [[ -f "$pid_file" ]] || return 4
   pid="$(cat "$pid_file")" || return 5
   kill -0 "$pid" >/dev/null 2>&1 || return 6
}

msgdispatcher_init() {
   output_tool="/usr/lib/msgcollector/msgcollector"
   output_general="output_func_general"
   output_x="output_func_x"
   output_cli="output_func_cli"
}

msgdispatcher_wait() {
   while true; do
      if msgdispatcher_pid_check "x" ; then
         msgdispatcher_running_x="true"
      fi
      if msgdispatcher_pid_check "cli" ; then
         msgdispatcher_running_cli="true"
      fi
      if [ "$msgdispatcher_running_x" = "true" ] || [ "$msgdispatcher_running_cli" = "true" ]; then
         break
      fi
      sleep "2" &
      lastpid="$!"
      wait "$lastpid" || break
   done
}

output_func_general() {
   output_func ${1+"$@"}
   return "$?"
}

output_func_x() {
   if [ "$msgdispatcher_running_x" = "true" ]; then
      output_func ${1+"$@"}
      return "$?"
   fi
   true "Skipping $FUNCNAME."
}

output_func_cli() {
   if [ "$msgdispatcher_running_cli" = "true" ]; then
      output_func ${1+"$@"}
      return "$?"
   fi
   true "$FUNCNAME: injecting --onlyecho."
   output_func --onlyecho ${1+"$@"}
}

output_func() {
   [ -n "$who_ami" ] || who_ami="$(whoami)"

   if [ "$output_func_verbose" = "true" ]; then
      echo "Running: bash -x $output_tool --identifier $IDENTIFIER --whoami $who_ami ${1+$@}"
      bash -x $output_tool --identifier "$IDENTIFIER" --whoami "$who_ami" ${1+"$@"}
   else
      $output_tool --identifier "$IDENTIFIER" --whoami "$who_ami" ${1+"$@"}
   fi
   return "$?"
}
