#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2018 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -e

who_ami="$1"
identifier="$2"
progressbaridx="$3"

if [ -f "/var/run/msgcollector/$who_ami/${identifier}.${progressbaridx}.parentpid" ]; then
   parentpid="$(cat "/var/run/msgcollector/$who_ami/${identifier}.${progressbaridx}.parentpid")"

   ## Check if still running.
   ps__p_exit_code="0"
   ps -p "$parentpid" >/dev/null 2>/dev/null || { ps__p_exit_code="$?"; true; };

   if [ "$ps__p_exit_code" = "0" ]; then
      true "$output_signal_caught caught. Sending signal sigusr2 to $parentpid."
      kill -sigusr2 "$parentpid"
   else
      true "$output_signal_caught caught. Not sending signal sigusr2 to parentpid $parentpid, because it is already terminated."
   fi
fi
