#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -e

who_ami="$1"
identifier="$2"
progressbaridx="$3"

if [ -f "/run/msgcollector/$who_ami/${identifier}_${progressbaridx}_parentpid" ]; then
   parentpid="$(cat "/run/msgcollector/$who_ami/${identifier}_${progressbaridx}_parentpid")"

   ## Check if still running.
   ps__p_exit_code="0"
   ps -p "$parentpid" >/dev/null 2>/dev/null || { ps__p_exit_code="$?"; true; };

   if [ "$ps__p_exit_code" = "0" ]; then
      true "$output_signal_caught caught. Sending signal sigusr2 to $parentpid."
      kill -s sigusr2 "$parentpid"
   else
      true "$output_signal_caught caught. Not sending signal sigusr2 to parentpid $parentpid, because it is already terminated."
   fi
fi
