#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -e

check() {
   if ! [[ "$1" =~ ^[0-9a-zA-Z_-]+$ ]]; then
      echo "Invalid character!" >&2
      echo "\$1: $1" >&2
      exit 1
   fi
}

who_ami="$1"
identifier="$2"
progressbaridx="$3"

check "$who_ami"
check "$identifier"
check "$progressbaridx"

if [ -f "/run/msgcollector/$who_ami/${identifier}_${progressbaridx}_parentpid" ]; then
   parentpid="$(cat "/run/msgcollector/$who_ami/${identifier}_${progressbaridx}_parentpid")"

   true "parentpid: '$parentpid'"

   if [[ ! "$parentpid" == *[!0-9]* ]]; then
      true "parentpid is strictly numeric, ok."
   else
      true "parentpid is not strictly numeric, exit."
      exit 0
   fi

   ## Check if still running.
   ps__p_exit_code="0"
   ps -p "$parentpid" >/dev/null 2>/dev/null || { ps__p_exit_code="$?"; true; };

   if [ "$ps__p_exit_code" = "0" ]; then
      true "Sending signal sigusr2 to $parentpid."
      kill -s sigusr2 "$parentpid"
   else
      true "Not sending signal sigusr2 to parentpid $parentpid, because it is already terminated."
   fi
fi
