#!/bin/bash

## Copyright (C) 2012 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -e

while read -r line; do
   percent="$line"
   eval $pv_echo_command
   eval $pv_wrapper_command
done
