#!/usr/bin/python3 -u

## Copyright (C) 2014 troubadour <trobador@riseup.net>
## Copyright (C) 2014 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>

def strip():
    ## Strip html
    stripped_message=re.sub('<[^<]+?>', '', html)
    ## Retrieve the "escaped" colons used in yaml text.
    message = re.sub('&#58;', ':', stripped_message)
    print(message)

if __name__=='__main__':
    import sys,  re
    html = sys.argv[1]
    strip()
